service:
    name: harness_cicdtestingproject
    identifier: cicdtestingproject
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: cicdtestingproject
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: Git-Connector
                            gitFetchType: Branch
                            paths:
                                - CICD-TestingProject/pod.yaml
                                - CICD-TestingProject/kubernetes-service.yml
                            repoName: harnesscd-example-apps
                            branch: main
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false